``` Códigos SQL para criar o banco e as tabelas

create table if not exists clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text not null,
  email text not null unique,
  created_at timestamp with time zone default now()
);



create table if not exists servicos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  preco numeric(10,2) not null,
  duracao_minutos integer not null,
  ativo boolean default true,
  created_at timestamp with time zone default now()
);



create table if not exists agendamentos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id) on delete cascade,
  data date not null,
  horario text not null,
  status text not null default 'pendente',
  observacoes text,
  created_at timestamp with time zone default now()
);



create table if not exists agendamento_servicos (
  id bigint generated by default as identity primary key,
  agendamento_id bigint not null references agendamentos(id) on delete cascade,
  servico_id bigint not null references servicos(id) on delete cascade,
  status_servico text not null default 'pendente',
  created_at timestamp with time zone default now()
);



insert into servicos (nome, descricao, preco, duracao_minutos)
values
  ('Corte Feminino', 'Corte com atenção aos detalhes', 70.00, 60),
  ('Escova', 'Finalização para alinhar os fios', 45.00, 40),
  ('Manicure', 'Cuidado especial para as unhas', 35.00, 45),
  ('Hidratação', 'Tratamento para brilho e maciez', 60.00, 50),
  ('Design de Sobrancelha', 'Modelagem para valorizar o olhar', 30.00, 30),
  ('Lash Design', 'Realce dos cílios com acabamento delicado', 90.00, 90),
  ('Unha de Gel', 'Alongamento e acabamento duradouro', 120.00, 120),
  ('Progressiva', 'Alinhamento dos fios e redução de volume', 150.00, 180);



alter table clientes enable row level security;
alter table servicos enable row level security;
alter table agendamentos enable row level security;
alter table agendamento_servicos enable row level security;



create policy "permitir ler servicos"
on servicos for select
to anon, authenticated
using (true);



create policy "permitir inserir clientes"
on clientes for insert
to anon, authenticated
with check (true);



create policy "permitir ler clientes"
on clientes for select
to anon, authenticated
using (true);



create policy "permitir inserir agendamentos"
on agendamentos for insert
to anon, authenticated
with check (true);



create policy "permitir ler agendamentos"
on agendamentos for select
to anon, authenticated
using (true);



create policy "permitir atualizar agendamentos"
on agendamentos for update
to anon, authenticated
using (true)
with check (true);



create policy "permitir inserir agendamento_servicos"
on agendamento_servicos for insert
to anon, authenticated
with check (true);



create policy "permitir ler agendamento_servicos"
on agendamento_servicos for select
to anon, authenticated
using (true);



create policy "permitir atualizar agendamento_servicos"
on agendamento_servicos for update
to anon, authenticated
using (true)
with check (true);